name: Check File Changes on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main  # Change this to your target branch

jobs:
  check-file-changes:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch enough history to compare with the base branch
          fetch-depth: 0

      - name: Check for changes to specific file
        id: check-changes
        run: |
          # Define the file you want to monitor
          TARGET_FILE="Dockerfile"

          # Get the base branch (usually main)
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"

          # Get the merge commit SHA
          MERGE_SHA="${{ github.event.pull_request.merge_commit_sha }}"

          # Check if the target file was changed in this PR
          if git diff --name-only "origin/$BASE_BRANCH" "$MERGE_SHA" | grep -q "^$TARGET_FILE$"; then
            echo "File $TARGET_FILE was changed in this PR"
            echo "file_changed=true" >> $GITHUB_OUTPUT
            echo "changed_file=$TARGET_FILE" >> $GITHUB_OUTPUT
          else
            echo "File $TARGET_FILE was not changed in this PR"
            echo "file_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Take action if file was changed
        if: steps.check-changes.outputs.file_changed == 'true'
        run: |
          echo "🚨 Important file was modified: ${{ steps.check-changes.outputs.changed_file }}"
          echo "Taking appropriate action..."

      - name: No action needed
        if: steps.check-changes.outputs.file_changed == 'false'
        run: |
          echo "✅ No changes to monitored file - no action needed"
